# Site settings
title: Chowdown
email: maartenpaauw@gmail.com
description: The plain text recipe database for hackers
baseurl: ""
twitter_username: maartenpaauw
github_username:  maartenpaauw

# Build settings
markdown: kramdown
theme: chowdown

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
